# Generated by Django 2.2.12 on 2020-05-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('link', models.URLField(max_length=500, null=True)),
                ('logo', models.ImageField(upload_to='')),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('testimonio', models.CharField(blank=True, max_length=400, null=True)),
                ('testimonio_es', models.CharField(blank=True, max_length=400, null=True)),
                ('testimonio_en', models.CharField(blank=True, max_length=400, null=True)),
                ('autor', models.CharField(max_length=400, null=True)),
                ('fecha', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Aliado',
                'verbose_name_plural': 'Aliados',
            },
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('nombre_es', models.CharField(max_length=40, null=True)),
                ('nombre_en', models.CharField(max_length=40, null=True)),
                ('dato', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Número',
                'verbose_name_plural': 'Números',
            },
        ),
        migrations.CreateModel(
            name='Prensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('link', models.URLField(max_length=500)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo_es', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo_en', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion_es', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion_en', models.CharField(blank=True, max_length=300, null=True)),
                ('imagen', models.ImageField(default='pic_folder/None/partner-3.png', upload_to='prensa/')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Prensa',
                'verbose_name_plural': 'Prensa links',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePrograma', models.CharField(max_length=40, null=True)),
                ('nombrePrograma_es', models.CharField(max_length=40, null=True)),
                ('nombrePrograma_en', models.CharField(max_length=40, null=True)),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('descripcion_es', models.CharField(max_length=300, null=True)),
                ('descripcion_en', models.CharField(max_length=300, null=True)),
                ('order', models.IntegerField()),
                ('inicio', models.DateField()),
                ('lugar', models.CharField(max_length=100, null=True)),
                ('horas', models.IntegerField()),
                ('contenido', models.CharField(max_length=400, null=True)),
                ('contenido_es', models.CharField(max_length=400, null=True)),
                ('contenido_en', models.CharField(max_length=400, null=True)),
                ('requisitos', models.CharField(max_length=300, null=True)),
                ('requisitos_es', models.CharField(max_length=300, null=True)),
                ('requisitos_en', models.CharField(max_length=300, null=True)),
                ('patrocinador', models.CharField(max_length=300, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='programa/')),
                ('logo', models.ManyToManyField(to='tomillo.Aliado')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('texto', models.TextField()),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('fecha', models.DateField()),
                ('autor', models.CharField(max_length=50)),
                ('testimonio', models.BooleanField(default=False)),
                ('home', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRec', models.CharField(max_length=40)),
                ('nombreRec_es', models.CharField(max_length=40, null=True)),
                ('nombreRec_en', models.CharField(max_length=40, null=True)),
                ('archivo', models.FileField(null=True, upload_to='archivos/')),
                ('link', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='recimg/')),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tomillo.Programa')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePromo', models.CharField(max_length=40)),
                ('nombrePromo_es', models.CharField(max_length=40, null=True)),
                ('nombrePromo_en', models.CharField(max_length=40, null=True)),
                ('duracion', models.IntegerField()),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='edicion/')),
                ('foto', models.ManyToManyField(to='tomillo.Prensa')),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tomillo.Programa')),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('apellido', models.CharField(blank=True, max_length=25, null=True)),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('acerca_de', models.CharField(blank=True, max_length=550, null=True)),
                ('acerca_de_es', models.CharField(blank=True, max_length=550, null=True)),
                ('acerca_de_en', models.CharField(blank=True, max_length=550, null=True)),
                ('cv', models.FileField(null=True, upload_to='')),
                ('promocion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tomillo.Promocion')),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumnis',
            },
        ),
    ]
