# Generated by Django 2.2.12 on 2020-04-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('logo', models.ImageField(upload_to='')),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('testimonio', models.CharField(max_length=400, null=True)),
                ('autor', models.CharField(max_length=400, null=True)),
                ('fecha', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Aliado',
                'verbose_name_plural': 'Aliados',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('dato', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Número',
                'verbose_name_plural': 'Números',
            },
        ),
        migrations.CreateModel(
            name='Prensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('link', models.URLField(max_length=500)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(default='pic_folder/None/partner-3.png', upload_to='static/iemeges/')),
            ],
            options={
                'verbose_name': 'Prensa',
                'verbose_name_plural': 'Prensa links',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('duracion', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tomillo.Programa')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('texto', models.TextField()),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('fecha', models.DateField()),
                ('autor', models.CharField(max_length=50)),
                ('testimonio', models.BooleanField(default=False)),
                ('home', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('archivo', models.FileField(null=True, upload_to='')),
                ('link', models.URLField(max_length=500, null=True)),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tomillo.Promocion')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('acerca_de', models.CharField(max_length=250, null=True)),
                ('cv', models.FileField(null=True, upload_to='')),
                ('promocion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tomillo.Promocion')),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumnis',
            },
        ),
    ]
