# Generated by Django 2.2.12 on 2020-04-26 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tomillo', '0002_auto_20200407_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='prensa',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('precio', models.FloatField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('imagen', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='static/images/')),
                ('prensa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tomillo.Prensa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
