# Generated by Django 2.2.12 on 2020-05-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tomillo', '0002_auto_20200507_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tomillo.Programa'),
        ),
    ]
