# Generated by Django 2.2.12 on 2020-04-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomillo', '0003_auto_20200426_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prensa',
            name='nombre',
        ),
    ]
